services:
  reservations:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '3000:3000'
    env_file:
      - ./apps/reservations/.env
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    develop:
      watch:
        - action: sync
          path: ./apps/reservations
          target: /usr/src/app/apps/reservations
        - action: sync
          path: ./libs
          target: /usr/src/app/libs
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/reservations/package.json
        - action: rebuild
          path: ./package.json
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    develop:
      watch:
        - action: sync
          path: ./apps/auth
          target: /usr/src/app/apps/auth
        - action: sync
          path: ./libs
          target: /usr/src/app/libs
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/auth/package.json
        - action: rebuild
          path: ./package.json
  mongo:
    image: mongo
